using Cropbox
using CSV
using DataFrames
using d3PG
using Test
using TimeZones

@testset "d3PG" begin
    config = @config(
        :Clock => :step => 1u"d",
        :Calendar => :init => ZonedDateTime(1990, 6, 1, tz"Australia/Hobart"),
        :Climate => :data => CSV.File(joinpath(@__DIR__, "weather.csv")) |> DataFrame,
        :Parameters => (;
            :iAge => 730,
            :iWF => 4000,
            :iWR => 5000,
            :iWS => 4000,
            :iStemNo => 1430,
            :iASW => 190,
            :lat => -43.3,
            :FR => 1,
            :CO2 => 350,
            :maxASW => 190,
            :minASW => 190,
            :soilClass => 3,
            :irrigation => 0,
            :maxAge => 50,
            :nAge => 4,
            :rAge => 0.95,
            :fullCanAge => 3,
            :k => 0.5,
            :gammaR => 0.015,
            :SWconst0 => 0.7,
            :SWpower0 => 9,
            :fCalpha700 => 1.4,
            :fCg700 => 0.7,
            :maxIntcptn => 0.15,
            :LAImaxIntcptn => 0,
            :minCond => 0,
            :maxCond => 0.02,
            :LAIgcx => 3.33,
            :BLcond => 0.2,
            :coeffCond => 0.05,
            :y => 0.47,
            :tMax => 40,
            :tMin => 8.5,
            :tOpt => 16,
            :kF => 0,
            :pFS2 => 1,
            :pFS20 => 0.15,
            :aWs => 0.095,
            :nWs => 2.4,
            :pRx => 0.8,
            :pRn => 0.25,
            :m0 => 0,
            :fN0 => 1,
            :fNn => 0,
            :alphaCx => 0.06,
            :poolFractn => 0,
            :gammaN1 => 0,
            :gammaN0 => 0,
            :tgammaN => 0,
            :ngammaN => 1,
            :wSx1000 => 300,
            :thinPower => 3 / 2,
            :mF => 0,
            :mR => 0.2,
            :mS => 0.2,    
            :gammaF1 => 0.027,
            :gammaF0 => 0.001,
            :tgammaF => 12,
            :SLA0 => 11,
            :SLA1 => 4,
            :tSLA => 2.5,
            :fracBB0 => 0.75,
            :fracBB1 => 0.15,
            :tBB => 2,
            :rho0 => 450,
            :rho1 => 450,
            :tRho => 4,
            :aH => 0.6,
            :nHB => 1.2,
            :nHN => 0,
            :aV => 0,
            :nVB => 0,
            :nVN => 0,
            :Qa => -90,
            :Qb => 0.8,
            :gDM_mol => 24,
            :molPAR_MJ => 2.3
        )
    );

    visualize(Model, :standAge, [:WF, :WR, :WS, :W]; config, stop=3660, kind=:line)
end